#!/usr/bin/env python3
"""Редизайн предметов: The Four Veins, Dark Forest, Survivor Settlement.
Компасы: корпус перерисовывается, стрелка копируется 1:1 из кадров-доноров."""
import os
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
ITEM = os.path.join(ROOT, "src", "main", "resources", "assets", "opusvsexe",
                    "textures", "item")
EXP = os.path.join(ITEM, "expedition")
S = 32

def blit(pal, rows):
    im = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    px = im.load()
    for y, row in enumerate(rows[:S]):
        for x, ch in enumerate(row[:S]):
            if ch == "." or ch == " ":
                continue
            px[x, y] = pal[ch]
    return im.convert("RGBA")

def save(im, name):
    im.save(os.path.join(ITEM, name + ".png"))

# ============================================================
# THE FOUR VEINS — базальт/вулкан-чёрный + эмбер-швы + сера
# ============================================================
V = {
    ".": (0, 0, 0, 0),
    "K": (20, 14, 12), "D": (36, 26, 20), "V": (42, 30, 24), "v": (58, 44, 34),
    "G": (74, 58, 44), "E": (232, 129, 30), "e": (184, 94, 16), "W": (255, 227, 179),
    "C": (142, 31, 20), "c": (107, 22, 14), "S": (233, 198, 92), "z": (24, 18, 14),
    "d": (30, 22, 18), "q": (160, 100, 20), "R": (232, 129, 30), "r": (120, 60, 16),
    "g": (58, 44, 34),
}

# fire_essence: угольно-обсидиановая сфера с эмбер-жилами и раскалённым центром
save(blit(V, [
 "................................",
 "................................",
 "................................",
 "................................",
 "...........KKKKKKK.............",
 ".........KVVVVVVVVVK...........",
 "........KVVEEVVVVVVVK..........",
 ".......KVVEeEVVVVVVVVK.........",
 "......KVVEEEEEEEVVVVVK.........",
 "......KVEEEWWWEEEEVVK..........",
 ".....KVEEEWWWWEEEECVK..........",
 ".....KVeEWWWWWWEWEeCK.........",
 ".....KVEEWWEeEWEEWECK..........",
 ".....KVEeWEEWWEEWEECK..........",
 "......KVeEWEEWWEEeECK..........",
 "......KVVeEWeEeEEEVCK..........",
 ".......KVVVEEEEEEVVCK..........",
 "........KVVVVVVVVVCK...........",
 ".........KCVVVVVCCK............",
 "..........KKKKKKKK..............",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "fire_essence")

# fire_sword: вулканический металл + эмбер-прожилки
save(blit(V, [
 "................................",
 "................................",
 "................................",
 "........KDDDDDDDDDDDDDD........",
 ".......KDvDDDDDDDDDDDDD........",
 "......KDvDDEEEDDDDDDDDD........",
 ".....KDvDDDEEEEDDDDDDD ........",
 "....KDvDDDDEEEEEDDDDDD.........",
 "...KDvDDDDDEEEEEEDDDDD.........",
 "..KDvDDDDDDEEEEEEEDDDD.........",
 "..KDvDDDDDEEEEEEEEDDD..........",
 "..KDvDDDDEEEEEEEEEDD...........",
 "..KDvDDDEEEEEEEEEEd............",
 "..KDvDDEEEEEEVEESd.............",
 "..KDvDDEEEEEEVESSd..............",
 "..KDvDDEEEEEEVESd...............",
 "..KDvDDEEEEEEVEd................",
 "..KDvDDEEEEEEVd.................",
 "..KDvDDEEEEEEd..................",
 "..KDvDDEEEEEd...................",
 "..KDvDDEEEEd....................",
 "..KDvDDEEEe.....................",
 "..KDvDDEeEe.....................",
 "..KDvDEEeEe.....................",
 "..KDvDEeEeE.....................",
 "..KDvDeEeEe.....................",
 "..KDvEeEeEe.....................",
 "..KDvEeEeEe.....................",
 "..KDeEeEeEe.....................",
 "..KKKKKKKKKKKKKK................",
 "................................",
 "................................",
]), "fire_sword")

# fire_pickaxe
save(blit(V, [
 "................................",
 ".KDDDDDDDDDDDDDDDDDDDDK.........",
 ".KvDDDDDDDDDDDDDDDDDDDvK........",
 ".KvDDEEEEDDDDDDDDDDDDDvK........",
 ".KvDDEEEEEDDDDDDDDDDDDvK........",
 ".KvDDEEEEDDDDDDDDDDDDDvK........",
 "..KvDDDDDDDDDDDDDDDDDDvK........",
 "..KvDDDDDDDDDDDDDDDDDDvK........",
 "...KvDDDDDDDDDDDDDDDDvK.........",
 "....KvDDDDDDDDDDDDDDvK..........",
 ".....KvDDDDDDDDDDDDvK...........",
 "......KvDDDDDDDDDDvK............",
 ".......KvDDDDDDDDvK.............",
 "........KvDDDDDDvK..............",
 ".........KvDDDDvK...............",
 "..........KvDDvK................",
 "...........KvDvK................",
 "............KvvK................",
 "............KVERK..............",
 "...........KVEERK...............",
 "..........KVEeERK...............",
 ".........KVEeeEERK..............",
 "........KVEeeeEEERK.............",
 ".......KVEeeeEEEEERK............",
 "......KVEeeeEEEEEEERK...........",
 ".....KVEeeeEEEEEEEEERK..........",
 ".....KVEeeEEEEEEEEEERK..........",
 ".....KVeEEEEEEEEEEEeEK..........",
 "......KKKKKKKKKKKKKKK...........",
 "................................",
 "................................",
 "................................",
]), "fire_pickaxe")

# fire_axe
save(blit(V, [
 "................................",
 ".....KDDDDDDDDDDDDDDK............",
 "....KDVDDDDDDDDDDDDDDK...........",
 "...KDVDvDDDDDDDDDDDDDvK..........",
 "..KDVDVDvDDDDDDDDDDDDDK.........",
 "..KDVDVDvDDDEEEEDDDDvDK.........",
 "..KDVDVDDDEEEEEEEDDDDK..........",
 "..KDVDvDDEEEEEEEEEEvK...........",
 "..KDvDDDEEEEEEEEEEEK............",
 "..KDvDDEEEEEEEVEEDK.............",
 "..KDvDDEEEEEEEEVEeD..............",
 "..KDvDDEEEEEEEEVEeE..............",
 "..KDvDDEEEEEEEEVEeE..............",
 "..KDvDDEEEEEEEVVEEe..............",
 "..KDvDDEEEEEEVVEEEe..............",
 "..KDvDDEEEEEEVVEEEE..............",
 "..KDvDDEEEEEVVEEEEE..............",
 "..KDvDDEEEEVVEEEEEE..............",
 "..KDvDDEEEVVEEEEEEE..............",
 "..KDvDDEEVVEEEEEEEE..............",
 "..KDvDEEVVEEEEEEEEE..............",
 "..KDvEEVVEEEEEEEEEE..............",
 "..KDvEEVEEEEEEEEEEE..............",
 "..KDvEEEEEEEEEEEEEE..............",
 "..KDvEEEEEEEEEEEEEv..............",
 "..KDvEEEEEEEEEEEEvv..............",
 "..KDDDDDDDDDDDDDDDvv..............",
 "..KKKKKKKKKKKKKKKKKK..............",
 "................................",
 "................................",
 "................................",
 "................................",
]), "fire_axe")

# fire_shovel
save(blit(V, [
 "................................",
 "................................",
 "....KDDDDDDDDDDDDDDDDDK.........",
 "....KDvEEEEEEEEEEEEEvDK.........",
 "....KDvEEWEWEEWEWEEEvDK.........",
 "....KDvEEEEEEEEEEEEEvDK.........",
 "....KDDDDDDDDDDDDDDDDDK.........",
 "....KvDDDDDDDDDDDDDDDvK.........",
 "....KvDDDDDDDDDDDDDDDvK.........",
 "....KvDDDDDDDDDDDDDDDvK.........",
 "....KgDDDDDDDDDDDDDDDgK.........",
 ".....KgDDDDDDDDDDDDDgK..........",
 "......KgDDDDDDDDDDDgK...........",
 ".......KgDDDDDDDDDgK............",
 "........KgDDDDDDDgK.............",
 ".........KgDDDDDgK..............",
 "..........KgDDDgK...............",
 "...........KgDgK................",
 "............KggK.................",
 "............KVERK...............",
 "...........KVEERK...............",
 "..........KVEeERK...............",
 ".........KVEeeEERK..............",
 "........KVEeeeEEERK.............",
 ".......KVEeeeEEEEERK............",
 "......KVEeeeEEEEEEERK...........",
 ".....KVEeeeEEEEEEEEERK..........",
 ".....KVEeEEEEEEEEEEeEK..........",
 "......KKKKKKKKKKKKKKK...........",
 "................................",
 "................................",
 "................................",
]), "fire_shovel")

# fire_hoe
save(blit(V, [
 "................................",
 "................................",
 ".....KDDDDDDDDDDDDDDDK...........",
 "....KDvDDDDDDDDDDDDDDDK..........",
 "....KDvDDDDDEEEDDDDDDvK..........",
 "....KDvDDDDDEEEEDDDDDDK.........",
 "....KDvDDDDDEEEEDDDDDDK..........",
 "....KDvDDDDDDDDDDDDDDK...........",
 "....KDvDDDDDDDDDDDDDvK...........",
 "....KDvDDDDDDDDDDDDvK............",
 "....KDvDDDDDDDDDDDDK.............",
 "....KDvDDDDDDDDDDDDK..............",
 "....KDvDDDDDDDDDDDvK..............",
 "....KDvDDDDDDDDDDvK...............",
 "....KDvDDDDDDDDDvK................",
 "....KDvDDDDDDDDvK.................",
 "....KDvDDDDDDDvK..................",
 "....KDvDDDDDDvK...................",
 "....KDvDDDDDvK....................",
 "....KDvDDDDvK.....................",
 "....KDvDDDvK......................",
 "....KDvDDvK.......................",
 "....KDvDvK........................",
 "....KDDK.........................",
 "....KDK..........................",
 "....KK...........................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "fire_hoe")

def vein_helm():
    return blit(V, [
     "................................",
     "..............KKKK............",
     ".............KVEeEK...........",
     "...........KVeEEEEEK..........",
     "..........KVvEEEEEEEK.........",
     ".........KDvEEEEEEEEEK........",
     "........KDDvEEEEEEEEEDK.......",
     "........KDDDDDDDDDDDDDK.......",
     "........KDDDvDDDDDDDDvK.......",
     ".......KDDDKDvvvvvDKDvDK......",
     ".......KDDDKzzzzzzDKDDK.......",
     ".......KDDDKzEzEzKDDDK........",
     ".......KDDDKzEeEzKDDDK........",
     ".......KKKKKKKKKKKKKKK........",
     "........KDDDDDDDDDDDK.........",
     ".......KDDDKKDDDKKDDDK........",
     "......KDDDKGDDDDDDGKDDDK......",
     ".....KDdDKGDDDDDDDDGKDDDK.....",
     "....KDdDDGDDDDDDDDDDGDDDDK....",
     "....KDDDDDDDDDDDDDDDDDDDK.....",
     "....KDDDDDDDDDDDDDDDDDDDK.....",
     "....KDdDKGDDDDDDDDDDGKDDdK....",
     ".....KDDDGDDDDDDDDDDGKDDD.....",
     ".....KDDDDDDDDDDDDDDDDDK......",
     ".......KKKKKKKKKKKKKKK........",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(vein_helm(), "fire_helmet")

def vein_chest():
    return blit(V, [
     "................................",
     "..........K........K..........",
     ".........KKK......KKK.........",
     "........KVEK....KVEK.........",
     ".......KVEeEK..KVEeEK........",
     ".......KVVvEEKKEEvVVK........",
     ".......KDDDEEEEEEDDDDK........",
     ".......KDDDDEDDDEDDDDK........",
     ".......KDDDDEEDDEEDDDK........",
     "........KDDEEEDDDDK...........",
     "........KDDEDDDDDDK...........",
     "........KDDEzKzEDDK...........",
     "........KDDEzzzEDDK...........",
     "........KDDEzzzEDDK...........",
     "........KDDDDDDDDDK...........",
     ".........KDDDKKDDDK...........",
     "..........KDDDDDDK............",
     "...........KDDDDK.............",
     ".......KKKKDDDDDDKKKK.........",
     "......KDDKKDDDDDDKKDDK........",
     ".....KDDDDKDDDDDDKDDDDK.......",
     "....KDDDDDKDDDDDDKDDDDDK......",
     "....KDDDDKKDDDDDDKKDDDDK......",
     "...KDDDDKDDEEEEEEDDKDDDDK.....",
     "...KDDKDDDDDDDDDDDDDKDDK......",
     "...KKKDDDDDDDDDDDDDDDDKKK.....",
     "...KDDDDDDDDDDDDDDDDDDDDK.....",
     "....KKKKKKKKKKKKKKKKKKKK......",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(vein_chest(), "fire_chestplate")

def vein_legs():
    return blit(V, [
     "................................",
     "................................",
     "....KDDDDDDDDDDDDDDDDK.........",
     "....KDDDDDDDDDDDDDDDDK.........",
     "....KDDDDDKKKKKKDDDDDK.........",
     "....KDDDKDDDDDDDDDDKDDK........",
     "....KDDKDDEEEEEEEDDKDDK........",
     "....KDDKDDEEEEEEEDDKDDK........",
     "....KDDKDDDEDDDEDDKDDK.........",
     ".....KDDDDDDDDDDDDDDDK.........",
     ".....KDDDDDDDDDDDDDDDK.........",
     "......KKKKDDDDDDKKKK.........",
     "....KDDDDDKDDDDKDDDDDK........",
     "....KDDDDDDKDDKDDDDDDK........",
     ".....KDDDDKDDDDKDDDDK.........",
     ".....KKKKDDDDDDKKKK...........",
     "........KDDDDDDDDK............",
     "........KDDDDSDDDK............",
     "........KDDDSDSDK.............",
     "........KDDDDDDDK.............",
     "........KDDDDDDDK.............",
     "........KDDDEDDDK.............",
     "........KDDDEDDDK.............",
     "........KDDDDDDDK.............",
     "........KDDDDDDDK.............",
     "........KDDDDDDDK.............",
     "........KDDDDDDDK.............",
     "........KKKKKKKKK.............",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(vein_legs(), "fire_leggings")

def vein_boots():
    return blit(V, [
     "................................",
     "................................",
     ".....KDDDDDDDDDDDDDDK.........",
     ".....KDDDDDDDDDDDDDDK.........",
     ".....KDDDDDKKKKDDDDDK.........",
     ".....KDDKDDDDDDDDKDDK.........",
     ".....KDDKDEeeeEDDKDDK.........",
     ".....KDDDDDDDDDDDDDDK.........",
     ".....KDDDDDDDDDDDDDDK.........",
     ".....KDKKDDDDDDDDKKDK.........",
     "....KDvDKDDDDDDDDKDvDK........",
     "...KEEDDDDDDDDDDDDDDEEK.......",
     "..KEEEDDDDDDDDDDDDDDDEEK......",
     "..KEEvDDDDDDDDDDDDDvDDK.......",
     "..KEEvDDDDDDDDDDDDDvDDK.......",
     "..KEDDDDDDDDDDDDDDDDDDK.......",
     "..KDDDDDDDDDDDDDDDDDDDK.......",
     "..KKKDDDDDDDDDDDDDDDDDKK......",
     "..KDDDDDDDDDDDDDDDDDDDK.......",
     "..KDDDDvDDDDDDDDvDDDDDK.......",
     "..KKKKKKKKKKKKKKKKKKKKK.......",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(vein_boots(), "fire_boots")

# --- Ember (Retained, high tier): бордово-янтарная эмаль
E_P = dict(V)
E_P.update({
    "H": (122, 18, 32), "h": (88, 12, 24), "M": (152, 30, 40), "Y": (255, 185, 62),
    "L": (240, 214, 128), "I": (160, 60, 48),
})

def ember_helm():
    return blit(E_P, [
     "................................",
     "..............KKKK............",
     ".............KYLLLKK..........",
     "...........KYLLLLLLK..........",
     "..........KHLLLLLLLMK.........",
     ".........KHMLLLLLLLMHK........",
     "........KHHMLLLLLLLHHHK.......",
     "........KHHHHHHHHHHHHHK.......",
     "........KHHHHKKKHHHHHHK.......",
     ".......KHIIKzzzzzKHHHHK.......",
     ".......KVIIKzEzEzKHHHK........",
     ".......KVIIKzEzEzKHHHK........",
     ".......KHHIIKKKKKHHHK.........",
     "........KHHHEEEHHHK...........",
     ".......KHHHKKHHKHHHK..........",
     "......KHHHKKHHHHKHHHK.........",
     ".....KHHHKKHHHHHHKHHHK........",
     "....KHHHKKHHHHHHHHKHHHK.......",
     "....KHHHHHHHHHHHHHHHHHHK......",
     "....KHHHHHHHHHHHHHHHHHHK......",
     "....KHMHHHHHHHHHHHHHHMHK......",
     "....KHHHHHHHHHHHHHHHHHHK......",
     ".....KHHHHHHHHHHHHHHHHK.......",
     ".....KKKKKKKKKKKKKKKKKK.......",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(ember_helm(), "ember_helmet")

def ember_chest():
    return blit(E_P, [
     "................................",
     "..........K........K..........",
     ".........KKK......KKK.........",
     "........KHEEK....KHEEK........",
     ".......KHHEEEK..KHEEHK........",
     ".......KHHHEEKKEEHHHK.........",
     ".......KHHHEEEEEHHHHK.........",
     ".......KHHHEEEEEEHHHK.........",
     ".......KHHHHEEEHHHHH K........",
     "........KHHHHEEHHHHK.........",
     "........KHHHHEEHHHHK.........",
     "........KHHHHKzKHHHHK.........",
     "........KHHHHKzKHHHHK.........",
     "........KHHHHKzKHHHHK.........",
     "........KHHHKKKKKHHHK.........",
     ".........KHHHKKKHHHK..........",
     "..........KHHHHHHHK...........",
     "...........KHHHHHK............",
     ".......KKKKHHHHHHKKKK.........",
     "......KHKKHHHHHHHHKKHK........",
     ".....KHHEKKHHHHHHKKEHHK.......",
     "....KHHEEKKHHHHHHKKEEHK.......",
     "....KHHEKHHHHHHHHHHKEHK.......",
     "...KHHHHKEEEEEEEEEEKHHHK......",
     "...KHKKHHHHHHHHHHHHHHKKHK.....",
     "...KKKHHHHHHHHHHHHHHHHKKK.....",
     "...KHHHHHHHHHHHHHHHHHHHHK.....",
     "....KKKKKKKKKKKKKKKKKKKK......",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(ember_chest(), "ember_chestplate")

def ember_legs():
    return blit(E_P, [
     "................................",
     "................................",
     "....KHHHHHHHHHHHHHHHHK.........",
     "....KHHHHHHHHHHHHHHHHK.........",
     "....KHHHHHKKKKKKHHHHHK.........",
     "....KHHHKHHHHHHHHHKHHK.........",
     "....KHHKHEEEEEEHHHKHHK.........",
     "....KHHKHEEEEEEHHHKHHK.........",
     ".....KHHHHHHHHHHHHHHHK.........",
     ".....KHHHHKKKKKKHHHHHK.........",
     "......KKKKHHHHHHKKKK...........",
     "....KHHHHHKHHHHKHHHHHK.........",
     "....KHHHHHHKHHKHHHHHHK.........",
     ".....KHHHHKHHHHKHHHHK..........",
     ".....KKKKHHHHHHKKKK............",
     "........KHHHHHHHK..............",
     "........KHHHHHHHK..............",
     "........KHHHHHHHK..............",
     "........KHHHYYHHK..............",
     "........KHHYYYHHK..............",
     "........KHHYYYHHK..............",
     "........KHHHHHHHK..............",
     "........KHHHHHHHK..............",
     "........KHHHHHHHK..............",
     "........KHHHHHHHK..............",
     "........KHHHHHHHK..............",
     "........KKKKKKKKK..............",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(ember_legs(), "ember_leggings")

def ember_boots():
    return blit(E_P, [
     "................................",
     "................................",
     ".....KHHHHHHHHHHHHHHK.........",
     ".....KHHHHHHHHHHHHHHK.........",
     ".....KHHHHHKKKKHHHHHK.........",
     ".....KHHKHEeEEEEHKHHK.........",
     ".....KHHKHEEEEEHKHHK...........",
     ".....KHHYHHHHHHHHHHYK.........",
     ".....KHYYHHHHHHHHHYYK.........",
     ".....KHYYKKHHHHKKYYK..........",
     "....KHYYYKHHHHHHKYYYK.........",
     "...KHYYYYKHHHHHHKYYYYK........",
     "...KHYYYKHHHHHHHHKYYYK........",
     "...KHYYKHHHHHHHHHHKYYK........",
     "...KHHKHHHHHHHHHHHHKHHK.......",
     "...KHKHHMHHHHHHMHHHKHK........",
     "...KKKHHHHHHHHHHHHHHKKK.......",
     "...KHHHHHHHHHHHHHHHHHHK.......",
     "...KHHHHHHHHHHHHHHHHHHK.......",
     "...KKKKKKKKKKKKKKKKKKKK.......",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(ember_boots(), "ember_boots")

# ============================================================
# DARK FOREST — ночь/мох/teal/серебро
# ============================================================
DF = {
    ".": (0, 0, 0, 0),
    "K": (12, 10, 16), "N": (18, 16, 26), "n": (28, 22, 38),
    "M": (98, 117, 56), "m": (74, 86, 41),
    "T": (100, 221, 225), "t": (63, 168, 184), "Y": (168, 237, 233),
    "W": (201, 213, 208), "w": (147, 165, 160),
    "B": (58, 46, 34), "b": (42, 32, 24), "E": (233, 242, 240), "z": (14, 12, 20),
    "y": (41, 62, 78),
}

# shade_silk: моток тёмного шелка с teal-нитью
save(blit(DF, [
 "................................",
 "................................",
 "..............................",
 "...........KKKKKKKKK............",
 ".........KKNNNNNNNNNNK..........",
 "........KNNNNNNNNNNNNNK.........",
 ".......KNNKNNNNNNNNNNNK.........",
 "......KNNKNNNNNNNNNNNNK.........",
 ".....KTNNNKnKnKNNNNNNNK.........",
 "....KTTNNKNNTNNTNNNNNNK.........",
 "....KTNNKNNNTTNNNNNNNNK.........",
 "....KTTKNnKNNTNNNNnNNK..........",
 "....KTTNNKNNTNNNNNNNNK..........",
 "....KTTNNKKNTTNNNNNNNK..........",
 "....KTTTNNNNNTTNNNNNNK..........",
 ".....KTTTTTTTTNNNNNNK...........",
 "......KKKKKKKTTNNNNK............",
 ".............KTTTK.............",
 "...............KKK..............",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "shade_silk")

# moonwing_membrane: membrane крыла с жилками
save(blit(DF, [
 "................................",
 "...........K...................",
 "..........KWYK.................",
 ".........KWWyyK................",
 "........KWWyyWww...............",
 ".......KWWTyyWwwK..............",
 "......KWWTyyyTwwK..............",
 ".....KWwTyyyTwwWwK.............",
 ".....KWwTyyyTTwwWK.............",
 ".....KWwTyyyTTwWwK.............",
 ".....KwTyyyTyyTTwK.............",
 "......KyyyTyyyTTTK.............",
 ".......KyyTyyyTTK..............",
 "........KyTyyywTK..............",
 ".........KyyywTK...............",
 "..........KyyTK................",
 "...........KyTK................",
 "............KwTK...............",
 ".............KwTK..............",
 "..............KwTK.............",
 "...............KTTK............",
 "................KTTK...........",
 ".................KTTK..........",
 "..................KTTK.........",
 "...................KTTK........",
 "....................KTTK.......",
 ".....................KTTK......",
 "......................KTTK.....",
 ".......................KKK.....",
 "................................",
 "................................",
 "................................",
]), "moonwing_membrane")

# moonflower_heart: сияющее серебристо-teal сердце лунного цветка
save(blit(DF, [
 "................................",
 "................................",
 "................................",
 "................................",
 "..........KKKKKKK..............",
 ".........KWWWWWWWK.............",
 "........KWWWWWWWWWK............",
 "........KWWWKKKKWWW............",
 ".......KWWTKKKKKWWW............",
 ".......KWWTKKKKKWWK............",
 ".......KWWTKKYKKWWK............",
 ".......KWWTKYYYKWWK............",
 ".......KWWTKYYYKWWK............",
 ".......KWWTKYYYKWWK............",
 ".......KWWTKYYYKWWK............",
 ".......KWWTKKYKKWWK............",
 ".......KWWTKKKKKWWK............",
 ".......KWWKKKKKKWWK............",
 "........KWWWWWWWWK.............",
 "........KKWWWWWKK..............",
 ".........KKKKKKK...............",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "moonflower_heart")

# rootbound_eye: дремотный корневой глаз с teal-зрачком
save(blit(DF, [
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "........KBBBBBBBBBBBK...........",
 ".......KBBBBBBBBBBBBBK..........",
 "......KbBBBKNNNNNKBBBbK.........",
 "......KBBNKNNNNNNNKBNBK.........",
 "......KBNKNNNNNNNNNKBNK.........",
 "......KBNKNNTTTNNNNKBNK.........",
 "......KBNKNTYYYYTNNKBNK.........",
 "......KBNKNTYEETYN KBNK.........",
 "......KBNKNTYYTYNNKBNK.........",
 "......KBNKNNTTTNNNNKBNK.........",
 "......KBNKNNNTNNNNNNKBNK........",
 "......KBNKNNNNNNNNKBNK..........",
 "......KBBNKNNNNNNKBNBK..........",
 ".......KBBBNKNNNKBBBK...........",
 "........KBBBbKBBBBK.............",
 ".........KKKKKKKKK..............",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "rootbound_eye")

# briarweave: плетение из тёмного терновника с шипами
save(blit(DF, [
 "................................",
 "................................",
 "..........KKK..................",
 "........KBBBBBBK...............",
 ".......KBBBBBBBBK..............",
 ".......KBmBBBmBBK..............",
 "......KBBBBBBBBBBK.............",
 "......KBBmBBBmBBBK.............",
 ".....KBBBBBBBBBBBBK............",
 ".....KBmBBBBBBmBBBK............",
 "....KBBBBBBBBBBBBBBK...........",
 "....KBBmBBmBBmBBBBK............",
 "...KBBBBBBBBBBBBBBBK...........",
 "...KBBBBBBBKBBBBBBBK...........",
 "..KBBBBBB BKBBBBBBBBK..........",
 "..KKKKKKKKK.KKKKKKKKK..........",
 "...KBBBBBBBBBK.................",
 "..KBBBBBBBBBBBK................",
 "..KBBmBBBmBBBBK................",
 ".KBBBBBBBBBBBBK................",
 ".KBBBBBBBBBBBBK................",
 ".KKKKKKKKKKKKK.................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "briarweave")

def briar_helm():
    return blit(DF, [
     "................................",
     "............KKK...............",
     "...........KBBBBK..............",
     "..........KBBBBBBK.............",
     ".........KBBBBBBBBK............",
     "........KBBBBBBBBBbK...........",
     "........KBBBBBKKBBBBK..........",
     ".......KBBBBKzzzKBBBK.........",
     ".......KBBBBKzTzKBBbK.........",
     ".......KBBBBKzTzKBBBK.........",
     ".......KBBKKKKKKKBBbK.........",
     "........KBBBBBBBBBBK...........",
     "........KBBTTBBTTBBK...........",
     ".......KBBBBBBBBBBBBbK.........",
     "......KBBBBBBBBBBBBBBK.........",
     ".....KbBBBBBBBBBBBBBBbK........",
     "....KBBBBBTBBBBBTBBBBBK........",
     "....KBBBBBBBBBBBBBBBBBBK.......",
     "....KBBbBBBBBBBBBBBBbBBK.......",
     "....KBBBBBBBBBBBBBBBBBBK.......",
     ".....KbBBBBBBBBBBBBBBbK........",
     ".....KBBBBBBBBBBBBBBBBK........",
     ".......KKKKKKKKKKKKKKK.........",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(briar_helm(), "briarweave_helmet")

def briar_chest():
    return blit(DF, [
     "................................",
     "..........K........K..........",
     ".........KKK......KKK.........",
     "........KBBBK.K..KBBBK........",
     ".......KBBBBBBK.KBBBBBK.......",
     ".......KBBBBBBBBBBBBBBBK......",
     ".......KbBBBBBBBBBBBBbBK......",
     ".......KBBBBKTTKTTKBBBBK......",
     ".......KBBBBKTTKTTKBBBBK......",
     "........KBBBBBBBBBBBBK........",
     "........KBBBBKKKKBBBBK........",
     "........KBBKzzzzzzKBBK........",
     "........KBBKzTTTTzKBBK........",
     "........KBBKzTTTTzKBBK........",
     "........KBBBKzzzzKBBBK........",
     ".........KBBBBKKBBBBK.........",
     "..........KBBBBBBBBK..........",
     "...........KbBbBbBbK..........",
     ".......KKKKKBBBBBBKKKKK.......",
     "......KBBKKBBBBBBBBKKBBK......",
     ".....KBBbBKBBBBBBBBKBbBBK.....",
     "....KBBBBBBKBBBBBBKBBBBBBK....",
     "....KBBBBBKKBBBBBBKKBBBBBK....",
     "...KBBBBKBBKTTTTTTKBBKBBBBK...",
     "...KBBBKBBBBBBBBBBBBBBKBBBK...",
     "...KKKBBBBBBBBBBBBBBBBBBKKK...",
     "...KBBBBBBBBBBBBBBBBBBBBBBK...",
     "....KKKKKKKKKKKKKKKKKKKKKK....",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(briar_chest(), "briarweave_chestplate")

def briar_legs():
    return blit(DF, [
     "................................",
     "................................",
     "....KBBBBBBBBBBBBBBBBK.........",
     "....KBBBBBBBBBBBBBBBBK.........",
     "....KBBBBBKKKKKKBBBBBK.........",
     "....KBBBKBBBBBBBBKBBBBK........",
     "....KBBKBBTBBBKBBTBBKBBK.......",
     "....KBBKBBTBBBBBBTBBKBBK.......",
     ".....KBBBBBBBKKBBBBBBBK........",
     ".....KBBBBBBBKKBBBBBBBK........",
     "......KKKKKBBBBKKKKK...........",
     "....KBBBBBBKBBBBKBBBBBB K......",
     "....KBBBBBBBKBBKBBBBBBBBK......",
     ".....KBBBBBBKBBBBBBBBBK........",
     ".....KKKKKKBBBBBBKKKKK.........",
     "........KBBBBBKBBBBBBK.........",
     "........KBBBBBBBBBBBBK.........",
     "........KBBBBBBBBBBBBK.........",
     "........KBBBBTBBBBTBBK.........",
     "........KBBBBBKBBBBBBK.........",
     "........KBBBBBBBBBBBBK.........",
     "........KBBBBBBBBBBBBK.........",
     "........KBBBBBBBBBBBBK.........",
     "........KBBBBBBBBBBBBK.........",
     "........KBBBBBBBBBBBBK.........",
     "........KBBBBBBBBBBBBK.........",
     "........KKKKKKKKKKKKK.........",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(briar_legs(), "briarweave_leggings")

def briar_boots():
    return blit(DF, [
     "................................",
     "................................",
     ".....KBBBBBBBBBBBBBBK..........",
     ".....KBBBBBBBBBBBBBBK..........",
     ".....KBBBBBKKKKBBBBBK..........",
     ".....KBBKBBBBBBBBKBBK..........",
     ".....KBBKBTTTTTTBKBBK..........",
     ".....KBBBBBBBBBBBBBBK..........",
     ".....KBBBBBBBBBBBBBBK..........",
     ".....KBBKKBBBBBBKKBBK..........",
     "....KBBKBBBBBBBBBBKBBK.........",
     "...KBBKBBBBBBBBBBBBKBBK........",
     "...KBBKbbBBBBBBBBbbKBBK........",
     "...KBBbBBBBBBBBBBBBbBBK........",
     "...KBBBBBBBBBBBBBBBBBBK........",
     "...KBBBKBBBBBBBBBBBBKBBK.......",
     "...KBBBKBBBBBBBBBBBBBBK.......",
     "...KKKKKBBBBBBBBBBBBBBK.......",
     "...KBBBBBBBBBBBBBBBBBBK.......",
     "...KBBBBbBBBBBBBBbBBBBBK.......",
     "...KKKKKKKKKKKKKKKKKKK........",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(briar_boots(), "briarweave_boots")

def vest_helm():
    return blit(DF, [
     "................................",
     "..............KKK..............",
     ".............KWWK.............",
     "...........KWWWWWK............",
     "..........KWWWWWWWK...........",
     ".........KWWWTTTWWWK..........",
     "........KWWWWTTTWWWWK.........",
     "........KWWWTKKKTWWWK.........",
     "........KWWWKTTTKWWWK.........",
     ".......KWWWKTTTTKWWWWK........",
     ".......KWWWKTTTTKWWWK.........",
     ".......KWWKKTTTTKKWWK.........",
     ".......KWWKKTTTTKKWWK.........",
     ".......KKKKKTTTTKKKKK.........",
     "........KWWWWTTWWWWK..........",
     ".......KWWWWKKKKWWWWK.........",
     "......KWWWwKWWWWKKWWWK........",
     ".....KWWWwKnnnnnKKWWWK........",
     "....KWWwwKnnnnnnnnnKWWWK.......",
     "....KWwwKnnTTTnnnnnKWWK.......",
     "....KwwKnnnTTTnnnnnKWWK........",
     "....KwKnnnnTTTnnnnnKWWK........",
     "....KKKnnnnnTTTnnnnnKWK........",
     ".......KKKKKKKKKKKKKKKK........",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(vest_helm(), "dark_forest_helmet")

def vest_chest():
    return blit(DF, [
     "................................",
     "..........K........K..........",
     ".........KKK......KKK.........",
     "........KWwK......KWWK........",
     ".......KnnKWK....KWWnnK.......",
     ".......KnnnKKWWWWKKnnnK.......",
     ".......KnTTnWWWWWWnTTnK.......",
     ".......KnTTnWWTTWWnTTnK.......",
     ".......KnnKKWWTTWWKKnnK.......",
     "........KnWWWWTTWWWWnK........",
     "........KWWWKKKKKKWWWK........",
     "........KWKTTTTTTTTKWK........",
     "........KWKTTTTTTTTKWK........",
     "........KWKTTTTTTTTKWK........",
     "........KWKKTTTTTTKKWK........",
     ".........KWKKWWWWKKWK.........",
     "..........KWWWWWWWWK..........",
     "...........KWWWWWWK...........",
     ".......KKKKKWWWWWWKKKKK.......",
     "......KWWKKWWWWWWWWKKWWK......",
     ".....KWWWWKWWWWWWWWKWWWWK.....",
     "....KWWWWWKWWWWWWWWKWWWWWK....",
     "....KWWWWKKWWWWWWWWKKWWWWK....",
     "...KWWWWKTTTTTWWTTTTTKWWWWK...",
     "...KWWKWWWWWWWWWWWWWWWWKWWK...",
     "...KKKWWWWWWWWWWWWWWWWWWKKK...",
     "...KWWWWWWWWWWWWWWWWWWWWWWK...",
     "....KKKKKKKKKKKKKKKKKKKKKK....",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(vest_chest(), "dark_forest_chestplate")

def vest_legs():
    return blit(DF, [
     "................................",
     "................................",
     "....KWWWWWWWWWWWWWWWWK.........",
     "....KWWWWWWWWWWWWWWWWK.........",
     "....KWWWWWKKKKKKWWWWWK.........",
     "....KWWWKWWWWWWWWKWWWK.........",
     "....KWWKTTTTTTTTTTKWWK.........",
     "....KWWKTTTTTTTTTTKWWK.........",
     ".....KWWWKKTTTTKKWWWK.........",
     ".....KWWWWWWKKWWWWWWK.........",
     "......KWWWWWWWWWWWWK...........",
     "....KWWWWWKKKWKKKKWWWWK........",
     "....KWWWWWWKKKKKKWWWWWK........",
     ".....KWWWWKKWWWWKKWWWK.........",
     ".....KKKKWWWWWWWWKKKK..........",
     "........KnnnnnnnnnnK...........",
     "........KnnnnnnnnnnK...........",
     "........KnnTTTTTTnnK...........",
     "........KnnTTTTTTnnK...........",
     "........KnnnTTTTnnnK...........",
     "........KnnnnnnnnnnK...........",
     "........KnnnnnnnnnnK...........",
     "........KnnnnnnnnnnK...........",
     "........KnnnnnnnnnnK...........",
     "........KnnnnnnnnnnK...........",
     "........KnnnnnnnnnnK...........",
     "........KKKKKKKKKKK............",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(vest_legs(), "dark_forest_leggings")

def vest_boots():
    return blit(DF, [
     "................................",
     "................................",
     ".....KWWWWWWWWWWWWWWK..........",
     ".....KWWWWWWWWWWWWWWK..........",
     ".....KWWWWWKKKKWWWWWK..........",
     ".....KWWKTTTTTTTTKWWK..........",
     ".....KWWKTTTTTTTTKWWK..........",
     ".....KWWWWWWWWWWWWWWK..........",
     ".....KWWWWWWWWWWWWWWK..........",
     ".....KWWKKWWWWWWKKWWK..........",
     "....KWWWKWWWWWWWWKWWWK.........",
     "...KWWWWKWWWWWWWWKWWWWK........",
     "...KWWWWKnnnnnnnnKWWWWK........",
     "...KWWWKnnnnnnnnnnKWWWK........",
     "...KWWKnnnnnnnnnnnnKWWK........",
     "...KWKnnnnnnnnnnnnnnKWK........",
     "...KWKnnnnnTTTnnnnnnKWK........",
     "...KKKKnnnnTTTnnnnnnKKK........",
     "...KnnnnnnTTTTTTnnnnnnK........",
     "...KnTTnnnTTTTTTnnnnnK.........",
     "...KKKKKKKKKKKKKKKKKKK.........",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(vest_boots(), "dark_forest_boots")

DFT = dict(DF)
DFT.update({"C": (90, 190, 220), "c": (60, 140, 180), "e": (120, 230, 235), "H": (70, 90, 40)})

def df_sword():
    return blit(DFT, [
     "................................",
     "................................",
     "................................",
     "........KNNNNNNNNNNNNNNN........",
     ".......KNNNNNNNNNNNNNNNN........",
     "......KNNNTTTNNNNNNNNNN........",
     ".....KNNNTTTTTNNNNNNNNN........",
     "....KNNNNTTTTTTNNNNNNNN........",
     "...KNNNNNTTTTTTTNNNNNNN........",
     "..KNNNNNNTTTTTTTNNNNNNN........",
     "..KnnTTTTTTTTTTTTNNNNN.........",
     "..KnnTTTTTTTTTTTTNNNNN.........",
     "..KnnTTTTTTTTTTTTNNNNN.........",
     "..KnnTTTTTCCCTTTTNNNNN.........",
     "..KnnTTTTCCCCTTTTNNNN.........",
     "..KnnTTTCCCCCCCTTTNNN.........",
     "..KnnTTCCCCCCCCCTTTNN.........",
     "..KnnTCCCCCCCCCCCTTTN.........",
     "..KnnCCCCCCCCCCCCTTTN.........",
     "..KnnCCCCCCCCCCCCCTTN.........",
     "..KnnCCCCCCCCCcCCCTN.........",
     "..KnnCCCCCCCcCCCCCCNN.........",
     "..KnnCCCCCcCCCCCCCNN..........",
     "..KnnCCCCcCCCCCCCNN...........",
     "..KnnCCCcCCCCCCCNN............",
     "..KnnCCcCCCCCCCNN.............",
     "..KnnCcCCCCCCCNN..............",
     "..KnCcCCCCCCCNN...............",
     "..KcCCCCCCCCCN................",
     "..KKKKKKKKKKKK................",
     "................................",
     "................................",
    ])
save(df_sword(), "dark_forest_sword")

def df_pickaxe():
    return blit(DFT, [
     "................................",
     ".KNNNNNNNNNNNNNNNNNNNNK........",
     ".KnNNNNNNNNNNNNNNNNNNnnK.......",
     ".KnNNTTTTNNNNNNNNNNNNnnK.......",
     ".KnNNTTTTNNNNNNNNNNNNnnK.......",
     ".KnNNTTTTNNNNNNNNNNNNnnK.......",
     "..KnNNNNNNNNNNNNNNNNNnnK.......",
     "..KnNNNNNNNNNNNNNNNNNnnK.......",
     "...KnNNNNNNNNNNNNNNNnnK........",
     "....KnNNNNNNNNNNNNNnnK.........",
     ".....KnNNNNNNNNNNNnnK..........",
     "......KnNNNNNNNNNnnK...........",
     ".......KnNNNNNNNnnK............",
     "........KnNNNNNnnK.............",
     ".........KnNNNnnK..............",
     "..........KnNnnK...............",
     "...........KnK................",
     "............KnnK................",
     "............KTTK................",
     "...........KTTTTK...............",
     "..........KTCCCTTK..............",
     ".........KTCcCCC TK.............",
     "........KTCCCCCCTTK............",
     ".......KTCCCCCCCCTTK...........",
     "......KTCCCCCCCCCCTTK..........",
     ".....KTCCCCCCCCCCCCCTK.........",
     ".....KTCCCCCCCCCCCCCTK.........",
     ".....KTTCCCCCCCCCCCTTK.........",
     "......KKKKKKKKKKKKKKK..........",
     "................................",
     "................................",
     "................................",
    ])
save(df_pickaxe(), "dark_forest_pickaxe")

def df_axe():
    return blit(DFT, [
     "................................",
     ".....KNNNNNNNNNNNNNNK...........",
     "....KnNNNNNNNNNNNNNNNK..........",
     "...KnNnNNNNNNNNNNNNNNnK.........",
     "..KnNnNnNNNNNNNNNNNNNK.........",
     "..KnNnNnNNNTTTTTNNNNNK.........",
     "..KnNnNNNTTTTTTTTTNNnK..........",
     "..KnNNTTTTTTTTTTTTNNK...........",
     "..KnNTTTTTTTTTTTTNNn............",
     "..KnTTCCCCCCCCCCTTNn............",
     "..KnTCCCCCCCCCCCTNNn............",
     "..KnTCCCCCCCCCCCTNNn............",
     "..KnTCCCCCCCCCCCTNNn............",
     "..KnTCCCCCCCCCCCTNNn............",
     "..KnTCCCCCCCCCCCTNNn............",
     "..KnTTCCCCCCCCCTNNn.............",
     "..KnnTTCCCCCCCTNNn..............",
     "..KnnTTCCCCCCTNNn...............",
     "..KnnTTCCCCTNNn.................",
     "..KnnTTCCCTNNn..................",
     "..KnnTTTCTNNn...................",
     "..KnnCCCTNNn....................",
     "..KnnCTTNNn.....................",
     "..KnnTTNNn......................",
     "..KnnTNNn.......................",
     "..KnnNNn........................",
     "..KnnNNn........................",
     "..KNNNNn........................",
     "..KKKKKKK........................",
     "................................",
     "................................",
     "................................",
    ])
save(df_axe(), "dark_forest_axe")

def df_shovel():
    return blit(DFT, [
     "................................",
     "................................",
     "....KNNNNNNNNNNNNNNNNNK.........",
     "....KnNTTTTTTTTTTTTTNnK.........",
     "....KnNTTYTTTTYTTTTNnK.........",
     "....KnNTTTTTTTTTTTTNnK.........",
     "....KNNNNNNNNNNNNNNNNK.........",
     "....KnnNNNNNNNNNNNNNnK.........",
     "....KnnNNNNNNNNNNNNNnK.........",
     "....KnnNNNNNNNNNNNNNnK.........",
     "....KnnNNNNNNNNNNNNNnK.........",
     ".....KnnNNNNNNNNNNNnK..........",
     "......KnnNNNNNNNNNnK...........",
     ".......KnnNNNNNNNnK............",
     "........KnnNNNNNnK.............",
     ".........KnnNNNnK..............",
     "..........KnnNnK...............",
     "...........KnnK................",
     "............KTTK...............",
     "...........KTTTTK..............",
     "..........KTCCCTTK.............",
     ".........KTCCCCCTTK............",
     "........KTCCCCCCCTTK...........",
     ".......KTCCCCCCCCCTTK..........",
     "......KTCCCCCCCCCCTTK..........",
     ".....KTCCCCCCCCCCCCTTK.........",
     ".....KTCCCCCCCCCCCCCTTK........",
     ".....KTTCCCCCCCCCCCTK..........",
     "......KKKKKKKKKKKKKKK..........",
     "................................",
     "................................",
     "................................",
    ])
save(df_shovel(), "dark_forest_shovel")

def df_hoe():
    return blit(DFT, [
     "................................",
     "................................",
     ".....KNNNNNNNNNNNNNNNK.........",
     "....KnNNNNNNNNNNNNNNNNK........",
     "....KnNNNTTTTTTTTNNNNnK........",
     "....KnNNTTTTTTTTTTNNN K........",
     "....KnNTTTTTTTTTTTTNN K........",
     "....KnTTTTTTTTTTTTNN K.........",
     "....KnTTCCCCCCCTTNn K..........",
     "....KnTCCCCCCCCCTNn K..........",
     "....KnTCCCCCCCCCTNn K..........",
     "....KnTCCCCCCCCCTNnK...........",
     "....KnTCCCCCCCCCTNnK...........",
     "....KnTTCCCCCCCTNnK............",
     "....KnnTTCCCCCTNnK.............",
     "....KnnTTCCCCTNnK..............",
     "....KnnTTCCCTNnK...............",
     "....KnnTCCCTNnK................",
     "....KnnCCCTNnK.................",
     "....KnnCCTNnK..................",
     "....KnnCTNnK...................",
     "....KnnTTNnK....................",
     "....KnnTNnK.....................",
     "....KnnNnK......................",
     "....KnnnK.......................",
     "....KKKKK........................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(df_hoe(), "dark_forest_hoe")

# ============================================================
# SURVIVOR SETTLEMENT — катаны
# ============================================================
SET = {
    ".": (0, 0, 0, 0),
    "K": (28, 27, 31), "S": (143, 149, 158), "s": (201, 205, 212),
    "W": (238, 241, 246), "I": (61, 90, 169), "i": (44, 66, 130),
    "Z": (199, 155, 80), "z": (150, 112, 52), "R": (184, 25, 66), "r": (140, 18, 50),
}

# katana: чёрная цуба, синяя ито, серебристый клинок
save(blit(SET, [
 "................................",
 "................................",
 "................................",
 "................................",
 ".......KsSSSSWWWSSSSsK...........",
 ".......KsSSSSWWWWSSSSsK..........",
 ".......KsWSWWWWWWWWSW K..........",
 ".......KsSWWWWWWWWWWS K..........",
 "......KsSSWWWWWWWWWSS K..........",
 "......KsSSWWWWWWWWSSS K..........",
 "......KsSWWWWWWWWWSSS K..........",
 "......KsSWWWWWWWWWSS ...........",
 "......KsWSSWWWWWWWS ............",
 "......KsSSWWWWWWSS ..............",
 "......KsSSWWWWWSSS ..............",
 "......KsWWWWWWWWWSS..............",
 "......KsWWWWWWWWWSS..............",
 "......KsSWWWWWWWWSS..............",
 "......KsSSWSSWWWSSS..............",
 "......KsSWSSSWWWSSS..............",
 "......KsSSSSWWWWSSS..............",
 "......KsSSSSWWWWSSS..............",
 "......KsWWSSWWWSSS..............",
 "......KsWWSSWWWSSS..............",
 "......KssSSSSSSSSSSsK.............",
 "......KSSSSSSSSSSSSSK.............",
 ".....KIIIIIIIIIIIIIIK............",
 ".....KIIIIIIIIIIIIIiK...........",
 ".....KzIIIIIIIIIIIIiK............",
 "....KzzzzzzzzzzzzzzzK............",
 "....KZZZZZZZZZZZZZZZK............",
 "....KKKKKKKKKKKKKKKKK............",
]), "katana")

# long_katana: длинный клинок, красная ито, золотая цуба
save(blit(SET, [
 "................................",
 "................................",
 "........KsSSSSSSSSSSSSsK.........",
 ".......KsSSSWWWWWWWWSSsK.........",
 "......KsSSSSWWWWWWWWWSSsK........",
 "......KsSSSWWWWWWWWWSSsK.........",
 "......KsSSWWWWWWWWWWWSsK.........",
 "......KsSSWWWWWWWWWWSSsK.........",
 "......KsSSWWWWWWWWWWSsK..........",
 "......KsSSWWWWWWWWWSSsK..........",
 "......KsSSWWWWWWWWWSSK...........",
 "......KsSSWWWWWWWWSSK............",
 "......KsSSWWWWWWWSSK.............",
 "......KsSSWWWWWWSSK..............",
 "......KsSSWWWWWSSK...............",
 "......KsSSWWWWSSK................",
 "......KsSSWWWSSK.................",
 "......KsSSWWSSK..................",
 "......KsSSWSSK...................",
 "......KsSSSSK....................",
 "......KsSSSSK....................",
 "......KsSSSSK....................",
 "......KsSSSSK....................",
 "......KsSSSSK....................",
 "......KssSSSSK...................",
 "......KSSSSSSK...................",
 ".....KIIIIIIIK...................",
 ".....KIIIIIIIiK..................",
 ".....KzIIIIIIIK..................",
 "....KzzzzzzzzzzK.................",
 "....KZZZZZZZZZZK.................",
 "....KKKKKKKKKKKKK................",
]), "long_katana")

# ============================================================
# COMPASSES — корпус перерисован, стрелка скопирована 1:1
# ============================================================

def load_donor(name):
    frames = [Image.open(os.path.join(EXP, f"{name}_{i:02d}.png")).convert("RGBA")
              for i in range(32)]
    W, H = frames[0].size
    common = [[frames[0].load()[x, y] for x in range(W)] for y in range(H)]
    const = [[True] * W for _ in range(H)]
    for f in frames:
        px = f.load()
        for y in range(H):
            for x in range(W):
                if px[x, y] != common[y][x]:
                    const[y][x] = False
    needle = []
    for f in frames:
        px = f.load()
        nf = []
        for y in range(H):
            for x in range(W):
                if not const[y][x] and px[x, y][3] > 0:
                    nf.append((x, y, px[x, y]))
        needle.append(nf)
    return frames, const, needle

def redraw_compass(name, ring, ring_hi, dial, dial_shade, accent, accent_dark, glyph):
    frames, const, needle = load_donor(name)
    out = []
    for fi in range(32):
        im = Image.new("RGBA", (32, 32), (0, 0, 0, 0))
        px = im.load()
        # корпус по исходному силуэту (кадры 32x32)
        for y in range(32):
            for x in range(32):
                if not const[y][x]:
                    continue
                d = (x - 16) * (x - 16) + (y - 16) * (y - 16)
                if d >= 220:
                    px[x, y] = ring
                elif d >= 178:
                    px[x, y] = ring_hi
                elif d >= 84:
                    px[x, y] = dial
                else:
                    px[x, y] = dial_shade
        # деления-тики и глифы (32-сетка)
        for (x, y) in ((8, 4), (12, 4), (16, 3), (20, 3), (24, 4), (28, 4),
                       (4, 10), (4, 14), (27, 10), (27, 14), (8, 28), (12, 28),
                       (20, 28), (24, 28), (6, 26), (26, 26), (4, 20), (28, 20),
                       (4, 24), (28, 24)):
            if const[y][x]:
                px[x, y] = accent
        for (gx, gy, ch) in glyph:
            if const[gy][gx]:
                px[gx, gy] = ch
        # стрелка 1:1 из исходного кадра
        for (x, y, c) in needle[fi]:
            px[x, y] = c
        out.append(im)
    for i, im in enumerate(out):
        im.save(os.path.join(EXP, f"{name}_{i:02d}.png"))
    print("compass:", name)

redraw_compass("opus_ruins_compass",
    (58, 55, 66), (92, 88, 108), (148, 132, 112), (116, 102, 86),
    (139, 89, 226), (99, 57, 180),
    [(16, 6, (139, 89, 226)), (17, 6, (139, 89, 226)), (16, 25, (111, 217, 255)), (17, 25, (111, 217, 255))])
redraw_compass("paradise_expedition_compass",
    (178, 158, 118), (216, 194, 148), (238, 226, 200), (208, 192, 162),
    (216, 168, 62), (168, 127, 40),
    [(16, 6, (216, 168, 62)), (17, 6, (216, 168, 62)), (16, 25, (44, 141, 114)), (17, 25, (31, 106, 85))])
redraw_compass("dark_forest_expedition_compass",
    (40, 46, 66), (70, 82, 112), (52, 62, 88), (36, 42, 62),
    (100, 221, 225), (63, 168, 184),
    [(16, 6, (168, 237, 233)), (17, 6, (100, 221, 225)), (16, 25, (98, 117, 56)), (17, 25, (74, 86, 41))])
redraw_compass("moon_fountain_expedition_compass",
    (128, 146, 152), (176, 198, 205), (214, 226, 228), (178, 194, 198),
    (150, 210, 216), (100, 168, 178),
    [(16, 6, (233, 242, 240)), (17, 6, (168, 237, 233)), (16, 25, (100, 221, 225)), (17, 25, (63, 168, 184))])

print("DONE:", len(os.listdir(ITEM)) - 118, "items + compasses")