#!/usr/bin/env python3
"""Редизайн предметных текстур 4 разделов (32x32 pixel-art, ASCII->палитра->PNG).
Sky Paradise / The Four Veins / Dark Forest / Survivor Settlement.
Компасы: корпус перерисован, стрелка скопирована 1:1 из существующих кадров
(функциональность поворота сохранена байт-в-байт)."""
import os, json
from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
ITEM = os.path.join(ROOT, "src", "main", "resources", "assets", "opusvsexe",
                    "textures", "item")
EXP = os.path.join(ITEM, "expedition")
S = 32

def fmt(im):
    return im.convert("RGBA")

def blit(pal, rows, outline=None):
    im = Image.new("RGBA", (S, S), (0, 0, 0, 0))
    px = im.load()
    for y, row in enumerate(rows[:S]):
        for x, ch in enumerate(row[:S]):
            if ch == "." or ch == " ":
                continue
            px[x, y] = pal[ch]
    return fmt(im)

def save(im, name):
    im.save(os.path.join(ITEM, name + ".png"))

# ============================================================
# SKY PARADISE — ivory/gold/jade/cyan/ruby, bronze intermediate
# ============================================================
P = {
    ".": (0, 0, 0, 0),
    "W": (244, 233, 209), "w": (217, 201, 166), "D": (184, 166, 127),
    "G": (216, 168, 62),  "g": (168, 127, 40),  "Y": (242, 208, 107),
    "J": (44, 141, 114),  "j": (31, 106, 85),   "Q": (91, 184, 148),
    "C": (111, 217, 255), "c": (63, 168, 216),
    "R": (192, 46, 58),   "r": (140, 31, 42),
    "B": (138, 90, 51),   "b": (106, 66, 38),   "Z": (181, 122, 69),
    "K": (43, 31, 20),    "A": (120, 86, 46),   "F": (250, 246, 236),
    "z": (30, 20, 14), "d": (26, 82, 78),
}
O = "K"

# --- paradise_fruit: свисающий золотисто-белый плод с циановым сердечком
save(blit(P, [
 "................................",
 "................................",
 "................................",
 "...........K....................",
 "...........KKK..K...............",
 "...........GKKKK.K..............",
 "............GGGYKK..............",
 "...........GYYYGKK..............",
 "..........GWWWYYWK..............",
 ".........GWcCWWYYWK.............",
 ".........GWcCWWYYWK.............",
 "........GWWcWYWYWYK.............",
 "........GWWWWWYYWGK.............",
 "........KGWYYWWWGWK.............",
 ".........KWYYWWGGK..............",
 "..........KWGWWGWK..............",
 "...........KKGDKWK..............",
 "............KKK.................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "paradise_fruit")

# --- sunfeather: золото-белое перо
save(blit(P, [
 "................................",
 "...........K....................",
 "..........KYK...................",
 ".........KYYWK..................",
 "........KYYWWWK.................",
 ".......KYWWWWWK.................",
 "......KYYWWWWWK.................",
 ".....KYYWWWWWWK.................",
 "....KYYWWWWWWWK.................",
 "...KYYWWWWWWWWK.................",
 "..KYYWWWWWWWWK..................",
 "..KYYWWWWWWWK...................",
 "..KYYWWWWWWWK...................",
 "...KYYWWWWWK....................",
 "....KYYWWWWK....................",
 ".....KYYWWWK....................",
 "......KYYWWK....................",
 ".......KYYWK....................",
 "........KYYK....................",
 ".........KYWK...................",
 "..........KYWK..................",
 "...........KYWK.................",
 "............KYK.................",
 ".............KYK................",
 "..............KYK...............",
 "...............KYK..............",
 "................KYK.............",
 ".................KWK............",
 "..................KK............",
 "................................",
 "................................",
 "................................",
]), "sunfeather")

# --- cloud_fleece: пушистое облако-сноп шерсти
save(blit(P, [
 "................................",
 "................................",
 "...........W.........W.........",
 "........WWRWwww...ww.wW........",
 ".......WWRWWWWWwwWWWWWWW.......",
 "......WWWWWWWWWWWWWWWWWWWW.....",
 ".....wwwWWWWWWWWWWWWWWWWww.....",
 "....wwWWWWWWWWWWWWWWWWWWWww....",
 "....wWWWWWWWWWWWWWWWWWWWWWw....",
 "...wWWWWWWWWWWWWWWWWWWWWWWWw...",
 "...WWWWWWWWWWWWWWWWWWWWWWWW....",
 "...WWWWWWWWWWWWWWWWWWWWWWWW....",
 "...WWWWWWWWWWWWWWWWWWWWWWWW....",
 "...wwWWWWWWWWWWWWWWWWWWWWww....",
 "....wwWWWWWWWWWWWWWWWWWWww.....",
 ".....wWWWWWWWWWWWWWWWWWWw......",
 "......wwWWWWWWWWWWWWWWww.......",
 ".......wwwwwWWWWWWwwww.........",
 "..........wwwwwwwww............",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "cloud_fleece")

# --- aerie_bronze_ingot: медный слиток с золотыми кантами
save(blit(P, [
 "................................",
 "................................",
 "................................",
 "................................",
 "........GKZKZGKKGZKZGK.........",
 ".......KZZZBBBBBBBBBBZK........",
 "......KZBBBBBBBBBBBBBBZK.......",
 ".....KZBBbBBBBBBBBbBBBBBK......",
 "....KZBBbBbbbbbbBBbBBBBBBK.....",
 "...KZZBBBBbBBBBbbBBbBBBBBKZg...",
 "..GKZZBBBBBBBBBBBBBBBBBBZKGg...",
 "..KZZBBBBBBbBBBBBbbBBBBBBZK....",
 ".KZBBBBBBBBBBBBBBBBBBBBBBBZK...",
 ".KZBBbBBbBBBBBBBbBBbBBBBBBZK...",
 "GZZBBBBBBBBBBBBBBBBBBBBBBZZg...",
 "KZZBBBBBBBBBBBBBBBBBBBBBBZZg...",
 "KZZBBBBBBBBBBBBBBBBBBBBBBZZK...",
 "GZZBBBBBBBBBBBBBBBBBBBBBBZZg...",
 ".KZBBBBBBBBBBBBBBBBBBBBBBZK....",
 ".KZBBbBBbBBBBBBBBBBBBBBBbZK....",
 "..KZZBBBBBBBBBBBBBBBBBBBBZK....",
 "..GKZZBBBBBBBBBBBBBBBBBBZKGg...",
 "...GKZZBBBBBBBBBBBBBBBBZKGg....",
 "....GKZZZZZZZZZZZZZZZZZKG......",
 ".....KgggggggggggggggggK.......",
 "..............................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "aerie_bronze_ingot")

def aerie_helm():
    return blit(P, [
     "................................",
     "..............KKKK............",
     ".............KZBBZK...........",
     "...........KBBBBBBBK..........",
     "..........KBBBBBBBBBK.........",
     ".........KBBbBBBBBBBBK........",
     "........KBBBBBBBBBBBBK........",
     "........KBBBBBBBBBBBBK........",
     ".......KBBBBBBBBBBBBBBK.......",
     ".......KBBBBKKKKKBBBBBK.......",
     ".......KBBKzzzzzKBBBBK........",
     ".......KBBKzzAzzKBBBbK........",
     ".......KBBKzzAzzKBBbBK........",
     ".......KKKKzzzzzKKBbBK........",
     "........KZZZKKKZZZBbBK........",
     ".......KZZZKKKKKZZZBBK........",
     "......KZZZKwwwwwwKBbBK........",
     ".....KZwwKwwwwwwwwKBBK........",
     "....KZwwwwwwwwwwwwwwKbK.......",
     "...KKwwwwwwwwwwwwwwwwKbK......",
     "..KwKwwwwwwwwwwwwwwwwKKK......",
     "..KKKwwwwwwwwwwwwwwwwwK.......",
     ".....KwKwwwwwwwwwwwKwK........",
     ".............................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(aerie_helm(), "aerie_bronze_helmet")

def aerie_chest():
    return blit(P, [
     "................................",
     "..........K........K..........",
     ".........KKK......KKK.........",
     "........KBBZK....KZBbK........",
     ".......KBBBBZK..KZBBBBK.......",
     ".......KBBBBBBKKBBBBBBK.......",
     ".......KBBbBBBBBBBBbBBK.......",
     ".......KBBBBBBBBBBBBBBK.......",
     ".......KBBBBBBBBBBBBBBK.......",
     "........KBBBBBBBBBBBBK........",
     "........KBBBBKKKKBBBBK........",
     "........KBBKzwwwwKBBBK........",
     "........KBBKzwwwwKBBBK........",
     "........KBBKzwwwwKBBBK........",
     "........KBBKzwwwzKBBbK........",
     ".........KBBKzzzKBBBK.........",
     "..........KBBBKKBBBK..........",
     "...........KBBBBBBK...........",
     ".......KKKKBBBBBBBBKKKK.......",
     "......KWWKKBBBBBBBBKKWWK......",
     ".....KWWWWKKBBBBBBKKWWWWK.....",
     "....KWWWWWKBBBBBBBBKWWWWWK....",
     "....KWWWWKKBBBBBBBBKKWWWWK....",
     "...KKWWWKBBBBBBBBBBBBKWWWKK...",
     "...KwKBBKBBBBBBBBBBBBKBBKwK...",
     "...KKKKBBBBBBBBBBBBBBBBKKKK...",
     "...KBBBBBBBBBBBBBBBBBBBBBBK...",
     "....KKKKKKKKKKKKKKKKKKKKKK....",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(aerie_chest(), "aerie_bronze_chestplate")

def aerie_legs():
    return blit(P, [
     "................................",
     "................................",
     "......KBBBBBBBBBBBBBBBBK.......",
     "......KBBBBBBBBBBBBBBBBK.......",
     "......KBBBBBKKKKKKBBBBBK.......",
     "......KBbBKwwwwKwwwwKBBK.......",
     "......KBBKwwwwwwwwwwKbBK.......",
     "......KBBKwwwwKzwwwwKBBK.......",
     ".......KKKKKKKKKKKKKKKK........",
     "........KKKKKKKKKKKKKK.........",
     "......KWWKKBBBBBBKKWWK.........",
     ".....KWWWWKKBBBBKKWWWWK........",
     ".....KWWWWKKBBBBKKWWWWK........",
     "......KWWKKKKBBKKKKWWK.........",
     "........KKKKKBBKKKKK...........",
     "..........KBBBBBK..............",
     "..........KBBBBBBK.............",
     "..........KBBBBBKK.............",
     "..........KBBBBK...............",
     "..........KBBBBK...............",
     "..........KBBBBK...............",
     "..........KBBBBK...............",
     "..........KBBBBK...............",
     "..........KBBBKK...............",
     "..........KBBBK................",
     "..........KBBK.................",
     "..........KBBK.................",
     "..........KKK..................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(aerie_legs(), "aerie_bronze_leggings")

def aerie_boots():
    return blit(P, [
     "................................",
     "................................",
     ".......KBBBBBBBBBBBBBBK........",
     ".......KBBBBBBBBBBBBBBK........",
     ".......KBBBBBKKKKBBBBBK........",
     ".......KBBKwwwwwwwwKBBK........",
     ".......KBBKwwwwwwwzKBBK........",
     ".......KBBBBBBBBBBBBBBK........",
     ".......KBBBBBBBBBBBBBBK........",
     ".......KZZKKBBBBBBKKZZK........",
     "......KZwwKBBBBBBBBKwwZK.......",
     ".....KZwwwKBBBBBbBBKwwwZK......",
     "....KZwwwwKKBBBBBBKKwwwwZK.....",
     "....KwwwwwwKBBBBBBKwwwwwwK.....",
     "....KwwwwwKBBBBBBBBKwwwwwK.....",
     "....KwwwwKBBBBBBBBBBKwwwwK.....",
     "....KwwKBBBBBBBBBBBBBBKwwK.....",
     "....KKKBBBBBBBBBBBBBBBBKKK.....",
     "....KBBBBBBBBBBBBBBBBBBBBK.....",
     "....KBBBBbBBBBBBBBbBBBBBBK.....",
     "....KKKKKKKKKKKKKKKKKKKKKK.....",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(aerie_boots(), "aerie_bronze_boots")

# --- seraphic_pinions: пара перьевых крыльев с рубиновой застёжкой
save(blit(P, [
 "................................",
 "................K...............",
 "................KYK.............",
 "................KYWYK..........",
 "...............KYWWWYK.........",
 "..............KYWWWWWYK........",
 ".............KYWWWWWWYK........",
 "............KYWWWWWWWYK........",
 "...........KYWWWWWWWWYK........",
 "..........KYWWWWWWWWWYK........",
 ".........KYWWWWWWWWWWYK........",
 "........KYWWWWWWWWWWWYK........",
 ".......KYWWWWWWWWWWWWYK........",
 "......KYWWWWWWWWWWWWWYK........",
 ".....KYWWWWWWWWWWWWWWYK........",
 "....KYWWWWWWWWWWWWWWWYK........",
 "....KYWWWWWWWWWWWWWWWYK........",
 ".....KRRKWWWWWWWWWWKYYK........",
 "......KRrRKWWWWWWWKYWWK........",
 ".......KRRRYKWWWWKYWWWK........",
 "........KRRRKWWWKYWWWWK........",
 ".........KRRKWWWKYWWWWK........",
 "..........KRRKYKYWWWWWK........",
 "...........KRKKYWWWWWWK........",
 "............KRYWWWWWWWK........",
 ".............KYWWWWWWWK........",
 "..............KWWWWWWWK........",
 "...............KWWWWWK.........",
 "................KWWWWK.........",
 ".................KWWK..........",
 "..................KK...........",
 "................................",
]), "seraphic_pinions")

# --- ruby_halo_shard: рубиновый сегмент ореола с золотой оковкой
save(blit(P, [
 "................................",
 "...........KKKKKKKK.............",
 "..........KRRRRRRRRK............",
 ".........KRRRRRRRRRRK...........",
 "........KRRRRRRRRRRRK...........",
 "........KrKrRRRRRKRrK...........",
 ".......KRRRRRRRRRRRRRK..........",
 ".......KrRRRRrKRRRRRrK..........",
 ".......KRRRRRRRRRRRRRK..........",
 ".......KRRrRRRKRRRRrRK..........",
 ".......KRRRRRRRRRRRRRK..........",
 ".......KrRrRRRRRRRRRrK..........",
 ".......KRRRRRRrRRRRRRK..........",
 "........KRRRRRRRRRRRK...........",
 "........KRRrrRRRRRRrK...........",
 ".........KRRRRRRRRRK............",
 "..........KRRRRRRRK.............",
 "...........KRRRRRK..............",
 "............KRRRK...............",
 ".............KRK................",
 "..............K.................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "ruby_halo_shard")

def parthenon_helm():
    return blit(P, [
     "................................",
     "..............KKKK............",
     ".............KGYGGK...........",
     "...........KGGWWWGGK..........",
     "..........KGGWWWWWGGK.........",
     ".........KGWwWWWWWWGGK........",
     "........KGWwWWWWWWWWGK........",
     "........KGWWWWWWWWWWWK........",
     "........KGWWCWWWWCWWWK........",
     ".......KGWWcWWWWcWWWWK........",
     ".......KGWWcKKKKcWWWWK........",
     ".......KGWWKJJJJKWWWK.........",
     ".......KGWWKJJJJKWWWK.........",
     ".......KGGGKKKKKKGGGK.........",
     "........KGGGDDDDGGGK..........",
     ".......KDDDGGKKGGDDDK.........",
     "......KGDDDDDDDDDDDDGK........",
     ".....KwDDDDDDDDDDDDDDK........",
     "....KwDDDDDDDDDDDDDDDDK.......",
     "....KDDRRDDDDDDDDDDDDDK.......",
     "....KDDDRrDDDDDDDDDDDDK.......",
     "....KwDDDDDDDDDDDDDDDDK.......",
     ".....KwwDDDDDDDDDDDDwwK.......",
     ".....KKwwwwwwwwwwwwwwKK.......",
     ".......KwwKKKKKKKKwwK.........",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(parthenon_helm(), "parthenon_helmet")

def parthenon_chest():
    return blit(P, [
     "................................",
     "..........K........K..........",
     ".........KGK......KGK.........",
     "........KGWGK....KGWGK........",
     ".......KGWWWGK..KGWWWGK.......",
     ".......KGWwWWGKKGWWwWGK.......",
     ".......KGGWWWWWWWWWWGGK.......",
     ".......KGGWWCCWWCCWWGGK.......",
     ".......KGGWWCCWWCCWWGGK.......",
     "........KGWWWWWWWWWWGK........",
     "........KGWWWKKKKWWWGK........",
     "........KGWKJDdJDKWWGK........",
     "........KGWKJJJJJJKWWGK.......",
     "........KGWKJJJJJJKWWGK.......",
     "........KGGKJRRKJJKWWGK.......",
     ".........KGGKRrRKJGGK.........",
     "..........KGGGKKGGGK..........",
     "...........KGGGGGGK...........",
     ".......KKKKGGGGGGGGKKKK.......",
     "......KDKKGGGGGGGGGGKKDK......",
     ".....KDDDDKGGGGGGGGKDDDDK.....",
     "....KDDDDDKGGGGGGGGKDDDDDK....",
     "....KDDDDKKGGGGGGGGKKDDDDK....",
     "...KGDDDKGGCCGGGGCCGGKDDDGK...",
     "...KwGKGGGGGGGGGGGGGGKGGKwK...",
     "...KKKGGGGGGGGGGGGGGGGGGKKK...",
     "...KGGGGGGGGGGGGGGGGGGGGGGK...",
     "....KKKKKKKKKKKKKKKKKKKKKK....",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(parthenon_chest(), "parthenon_chestplate")

def parthenon_legs():
    return blit(P, [
     "................................",
     "................................",
     ".....KGGGGGGGGGGGGGGGGK........",
     ".....KGGGGGGGGGGGGGGGGK........",
     ".....KGGGGGKKKKKKGGGGGK........",
     ".....KGGGKDDDDDDDDKGGGK........",
     ".....KGGKDDDDDDDDDDKGGK........",
     ".....KGGKJJKDDDDKJJKGGK........",
     ".....KGGKJJKDDDDKJJKGGK........",
     "......KGGKKKKKKKKKKGGK.........",
     "......KDDDKKGGGGKKDDDK.........",
     ".....KDDDDDKKGGKKDDDDDK........",
     ".....KDDDDDKKGGKKDDDDDK........",
     "......KDDDKKKKKKKKDDDK.........",
     "........KKKKKKKKKKKKK..........",
     "..........KDDDDDDK.............",
     "..........KDDDDDDDK............",
     "..........KDDDDDDKK............",
     "..........KDDDDDK..............",
     "..........KDDDDDK..............",
     "..........KDDDDDK..............",
     "..........KDDDDDK..............",
     "..........KDDDDDK..............",
     "..........KDDDDKK..............",
     "..........KDDDDK...............",
     "..........KDDDK................",
     "..........KDDDK................",
     "..........KKK.................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(parthenon_legs(), "parthenon_leggings")

def parthenon_boots():
    return blit(P, [
     "................................",
     "................................",
     "......KGGGGGGGGGGGGGGK.........",
     "......KGGGGGGGGGGGGGGK.........",
     "......KGGGGGKKKKGGGGGK.........",
     "......KGGKDDDDDDDDKGGK.........",
     "......KGGKJRRKJRRKGGK.........",
     "......KGGGGJJDDDDGGGK.........",
     "......KGGGGGGGGGGGGGGK.........",
     "......KDDDKKGGGGKKDDDK.........",
     ".....KDDDDDDKGGGGKDDDDDK.......",
     "....KDDDDDDDKGGGGKDDDDDDK......",
     "....KDDDDDKGGGGGGGGKDDDDK......",
     "....KDDDDKGGGGGGGGGGKDDDK......",
     "....KDDDKGGGGGGGGGGGGKDDDK.....",
     "....KDDKGGGGGGGGGGGGGGKDDK.....",
     "....KDKGGGGGGGGGGGGGGGGKDK.....",
     "....KKKGGGGGGGGGGGGGGGGKKK.....",
     "....KGGGGGGGGGGGGGGGGGGGGK.....",
     "....KGGGGgGGGGGGGGgGGGGGgK.....",
     "....KKKKKKKKKKKKKKKKKKKKKK.....",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
     "................................",
    ])
save(parthenon_boots(), "parthenon_boots")

TOOL = {  # общая основа для инструментов Parthenon
    "T": (244, 233, 209), "t": (217, 201, 166), "d": (184, 166, 127),
    "G": (216, 168, 62),  "g": (168, 127, 40),  "Y": (242, 208, 107),
    "J": (60, 180, 170),  "j": (36, 130, 130),  "C": (111, 217, 255),
    "K": (43, 31, 20),    "R": (192, 46, 58),   "r": (140, 31, 42),
    "W": (250, 246, 236),
    ".": (0, 0, 0, 0),
}

def _tool(rows):
    return blit(TOOL, rows)

# parthenon_sword: слоновая кость+золото, нефритовая рукоять, циановые каналы
save(_tool([
 "................................",
 "................................",
 "................................",
 "........KtttTTTTddddddddK.......",
 ".......KtttTTTTtttttddddK.......",
 "......KttTTTTTTttttttdddK.......",
 ".....KttTTTTTTtttttttTTtK.......",
 "....KttTTTTTTtttttttTTttK.......",
 "...KttTGTttTTtttttttttddK.......",
 "..KttTGYGGTttttttttttdddK.......",
 "..KttTGGGTtttttttttttddK........",
 "..KGYYYGGJtttttttttttddK........",
 "..KGCCCCCGJttttttttttdK.........",
 "...KGGGGGGJtttttttttdK..........",
 "....KJJJJJJttttttttdK...........",
 ".....KJJJJCttttttdGK............",
 "......KJJJJCttttdGGK............",
 ".......KJJJJCttdGGGK............",
 "........KJJJJCdGGGGK............",
 ".........KJJJJGGGGWK............",
 "..........KJJJGGGGW.............",
 "...........KJJGGG ..............",
 "............KjGG ...............",
 ".............K................................",
 "..............K................................",
 "...............K................................",
 "................K................................",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "parthenon_sword")

# parthenon_pickaxe
save(_tool([
 "................................",
 "..KTTTTTTTTTTTTTTTTTTTTK........",
 ".KgTTTTTTTTTTTTTTTTTTTTgK.......",
 ".KgTTYYYTTTTTTTTTTTTTTTgK.......",
 ".KgTTYYYTTTTTTTTTTTTTTTgK.......",
 "..KTTYYYTTTTTTTTTTTTTTTK........",
 "..KTTTTTTTTTTTTTTTTTTTTK........",
 "..KTTTTTTTTTTTTTTTTTTTTK........",
 "...KgTTTTTTTTTTTTTTTTgK.........",
 "....KgTTTTTTTTTTTTTTgK..........",
 ".....KgTTTTTTTTTTTTgK...........",
 "......KgTTTTTTTTTTgK............",
 ".......KgTTTTTTTTgK.............",
 "........KgTTTTTTgK..............",
 ".........KgTTTTgK...............",
 "..........KgTTgK................",
 "...........KgTgK................",
 "............KggK................",
 "............KGRK................",
 "...........KGGRRK...............",
 "..........KGGRRRRK..............",
 ".........KGGRRRRRRK.............",
 "........KGGRRRRRRRRK............",
 ".......KGGRRRRRRRRRRK...........",
 "......KGGRRRRRRRRRRRRK..........",
 ".....KGGRRRRRRRRRRRRRRK.........",
 ".....KGRGRRRRRRRRRRGRRK.........",
 "......KGGGGGGGGGGGGGGK..........",
 ".......KKKKKKKKKKKKKKK..........",
 "................................",
 "................................",
 "................................",
]), "parthenon_pickaxe")

# parthenon_axe
save(_tool([
 "................................",
 "......KTTTTTTTTTTTTTTTK.........",
 ".....KTGTgTTTTTTTTTTTTgTK........",
 "....KTGTGTGTTTTTTTTTTTTgTK.......",
 "...KTGTGTGTGttttttttttttgTK......",
 "..KTGTGTGTGTTttttttttttttTK......",
 "..KTGTGTGTTGttttttttttttTK.......",
 "..KGTGTGTTttttttttttttttK........",
 "..KGTGTTttttttttttttttTK.........",
 "..KGTTtttttttttttttttK...........",
 "..KTttttttttttttttttK............",
 "..KtttttttttttttttTK.............",
 "..KtttttttttttttttK..............",
 "..KtttttttttttttgGK..............",
 "..KttttttttttttgGGGK.............",
 "..KttttttttttttGGGGWK............",
 "..KtttttttttttGCGGGWK............",
 "..KttttttttttGCGGGGWK............",
 "..KtttttttttGCCGGGGWK............",
 "..KttttttttGCCGGGGGWK............",
 "..KtttttttGCCGGGGGWWK............",
 "..KttttttGCCGGGGGGWWK............",
 "..KtttttGCCGGGGGGGWWK............",
 "..KttttGCCGGGGGGGGWWK............",
 "..KtttGCCGGGGGGGGGWWK............",
 "..KttGCCGGGGGGGGGGWWK............",
 "..KGGGGGGGGGGGGGGGGGK............",
 "...KKKKKKKKKKKKKKKKK.............",
 "................................",
 "................................",
 "................................",
 "................................",
]), "parthenon_axe")

# parthenon_shovel
save(_tool([
 "................................",
 "................................",
 "....KtttttttttttttttttttK........",
 "....KtTTTYYYYTTTYYYYTTtK........",
 "....KtTTTYYYYTTTYYYYTTtK........",
 "....KtttttttttttttttttttK........",
 "....KtttttttttttttttttttK........",
 "....KtttttttttttttttttttK........",
 "....KtttttttttttttttttttK........",
 "....KgttttttttttttttttgK.........",
 ".....KgttttttttttttttgK..........",
 "......KgttttttttttttgK...........",
 ".......KgttttttttttgK............",
 "........KgttttttttgK.............",
 ".........KgttttttgK..............",
 "..........KgttttgK...............",
 "...........KgttgK................",
 "............KggK.................",
 "............KGRK.................",
 "...........KGGRRK................",
 "..........KGGRRRRK...............",
 ".........KGGRRRRRRK..............",
 "........KGGRRRRRRRRK.............",
 ".......KGGRRRRRRRRRRK............",
 "......KGGRRRRRRRRRRRRK...........",
 ".....KGGRRRRRRRRRRRRRRK..........",
 ".....KGRGRRRRRRRRRRGRRK..........",
 "......KGGGGGGGGGGGGGGK...........",
 ".......KKKKKKKKKKKKKKK...........",
 "................................",
 "................................",
 "................................",
]), "parthenon_shovel")

# parthenon_hoe
save(_tool([
 "................................",
 "................................",
 "......KTTTTTTTTTTTTTTTK.........",
 ".....KTgTTTTTTTTTTTTTTTTK........",
 "....KTgTTTTTTTTTTTTTTTTtK........",
 "....KTGTTTTTTttttttTTTTtK........",
 "....KGYGTGttttttttttttttK........",
 "....KGGGTttttttttttttttK.........",
 "....KgttttttttttttttttK..........",
 "....KttttttttttttttttK...........",
 "....KttttttttttttttTK............",
 "....KttttttttttttttK.............",
 "....KtttttttttttttK..............",
 "....KgttttttttttgGK..............",
 "....KGRtttttttggGGGK.............",
 "....KGRRGttttgGCCGGGK............",
 "....KGRRRRGgGGCCCCGGGK...........",
 "....KgRRRRRGCCCCCCGGGK...........",
 "....KgRrRRRRCCCCCCGGGK...........",
 "....KgRrRRRRCCCCCCGGGK...........",
 "....KgRRRRRRCCCCCCGGGK...........",
 "....KGRRRRRRCCCCCCGGGK...........",
 "....KgRRRRRRCCCCCCGGGK...........",
 "....KgRRRRRGCCCCCCGGGK...........",
 "....KgRRRRGCCCCCCGGGK............",
 "....KRRRRGGCCCCCGGGK.............",
 "....KKRRRKKKKKKKKKK..............",
 "................................",
 "................................",
 "................................",
 "................................",
 "................................",
]), "parthenon_hoe")

# Перенесённые иконки сохраняем в этот же скрипт:
# The Four Veins / Dark Forest / Settlement — см. gen_item_redesigns_2.py
print("paradise items:", len(os.listdir(ITEM)))